name = "refresh"
main = "src/index.ts"
account_id = "5c5263e05bb1e54242b1afb12a5c9259"

routes = [
  { pattern = "console.mytiki.com/api/latest/refresh", zone_id = "7be31970110fa56b1f8e1fe915a8b938" }
]

compatibility_date = "2023-02-02"

[vars]
L0_AUTH_URL = "https://auth.l0.mytiki.com/api/latest/oauth/token"
COOKIE = "refresh_token"
ORIGIN = "https://console.mytiki.com"
SECURE = true


